### ISSUE TITLE
PutObject need io.Pipe as intermediaries

### ISSUE THREAD

**Issue by iwanbk** [gigforks/minio#1]
0-stor's `client.Write` couldn't work directly with minio's `hash.Reader`.

It needs golang's `io.Pipe` as intermediaries to make it work

**Comment by lafont-e** [comment]
Iwan, I've been reading minio hash.Reader and the code it uses is just md5 and sha356 hashes as defined by the golang library, well, sha256 has an alternative implementation but only if your cpu has SSE or AVX instruccions.
Can you point me to a sample where I can see the issue ?

**Comment by iwanbk** [comment]
> Can you point me to a sample where I can see the issue ?

https://github.com/gigforks/minio/blob/baddab717b78e4c7a40406a25b8f24a0e0e0b5ef/cmd/gateway/zerostor/gateway-zerostor.go#L394-L404

See the last line, i expect it to use `hash.Reader` directly, like
```go
md, err := bkt.storCli.Write([]byte(object), data) 
```

**Comment by iwanbk** [comment]
Turned out to be a bug in 0-stor, fix attempt at https://github.com/zero-os/0-stor/pull/513

**Comment by iwanbk** [comment]
fixed at ddcbc727d280589c94629869c02cd17af58eceea
