### ISSUE TITLE
Revisit the bucket permissions/policies

### ISSUE THREAD

**Issue by iwanbk** [gigforks/minio#13]
We previously didn't support minio bucket policies.

Given the recent changes (handling bucket in gateway's meta instead of 0-stor), i think we could make improvement in this area

**Comment by iwanbk** [comment]
> Given the recent changes (handling bucket in gateway's meta instead of 0-stor), i think we could make improvement in this area

I think it is not good to keep the policy info in the bucket metadata because the policy could be changed by external tool.

The 0-db namespace also supposed to be managed by external tool, so we won't support setting policy.

What we will support:
- get policy : which will call 0-db [NSINFO](https://github.com/zero-os/0-db#nsinfo)
- anonymous object operation: and let the 0-db check the auth

**Comment by iwanbk** [comment]
> anonymous object operation: and let the 0-db check the auth

Latest minio doesn't support separate anonymous operation, so we won't implement it either

**Comment by zaibon** [comment]
what are the other mode minio implements ?

**Comment by iwanbk** [comment]
> get policy : which will call 0-db NSINFO

better to wait for https://github.com/zero-os/0-db/issues/23

**Comment by iwanbk** [comment]
> Latest minio doesn't support separate anonymous operation, so we won't implement it either

> what are the other mode minio implements ?

Need to check the other gateways code first.

Note that i didn't say that latest minio doesn't support anonymous operation, it just doesn't support **separate** operation.

https://github.com/gigforks/minio/blob/0bb624705637c658e1aef747564f7f6bd8dc727c/cmd/gateway-router.go#L48-L51

But in case of #14 will take too much time, do you OK if we stay with current version of minio @zaibon ?

**Comment by iwanbk** [comment]
it is already synced with latest minio at 72af0e646edd901a2181bd25c40eab024cb013e2 

Anonymous download still failed.

**Comment by iwanbk** [comment]
> Anonymous download still failed.

Asked on slack about this, waiting for the response.
Meanwhile i'll digging it by myself.

**Comment by zaibon** [comment]
For sure we won't wait for zero-os/0-db#23. Currently the managing tool is going to be 0-robot.
So we can already work over multiple 0-db instance no need to wait for special tools.

Can you write down exactly what feature you need, cause I don't really get what's missing now

**Comment by iwanbk** [comment]
> Can you write down exactly what feature you need, cause I don't really get what's missing now

It is only executing `NSINFO` against all 0-db instances.

Of course i can do it within gateway code, was just thinking to not duplicate the work.

**Comment by zaibon** [comment]
> It is only executing NSINFO against all 0-db instances.

ok let's do it from the gateway code for now, we can iterate on it in next version

**Comment by iwanbk** [comment]
> ok let's do it from the gateway code for now, we can iterate on it in next version

It works in `anonym-ops` branch.
Anonymous download also work fine.

Do we need to support setting bucket policy.
It is basically calling `NSSET` against all 0-db instances

I previously said in https://github.com/gigforks/minio/issues/13#issuecomment-370683160 that we shouldn't support setting policy, but i think the reason mentioned there is not valid, because we indeed doesn't need to keep the bucket policy in our metadata, we can simply request it to the servers.

**Comment by iwanbk** [comment]
Fixed at #17.

Please create other issue for set/del bucket policy

**Comment by zaibon** [comment]
I reopen this one cause I don't like how we mapped the bucker policy with the namespace rights.
These a 2 different things.
The minio gateway have access to a bunch of 0-db. So it is the gateway that decide who can write or not. This has nothing to do with the 0-db.

So the bucket policy needs to be managed 100% from the gateway code.
This will also make your live easier cause you don't have to do any calls on the 0-db to know or change a bucket policy.

**Comment by iwanbk** [comment]
hmm..yeah, it was my original idea. Questioned it yesterday 
https://github.com/gigforks/minio/issues/13#issuecomment-370683160.

But yeah, you're right. Will managed it fully on gateway's metadata

**Comment by iwanbk** [comment]
fixed (again) on #19
