### ISSUE TITLE
Minio should not fail to delete a file when the key is not found in zdb

### ISSUE THREAD

**Issue by zaibon** [gigforks/minio#31]
Scenario is: 
- upload a file
- clean up the 0-db data
- try to delete the file from minio

Expected result: file is deleted
Actual result: error saying that we can't find the key of the file.

**Comment by iwanbk** [comment]
From further test:
- just for comparison, the alibaba/aliyun (oss) gateway also return error
- the error didnt' come from `Delete` handler, but from ListObject handler.

Let me know if we you still think minio shouldn't return an error

**Comment by iwanbk** [comment]
> Let me know if we you still think minio shouldn't return an error

I think it shouldn't return error, i'll talk to minio dev

**Comment by zaibon** [comment]
I know the error comes from 0-stor. This behavior shouldn't happened in the first place it shows something is wrong. But at least if we don't return an error we can actually clean up the bucket. If we don't allow this. We'll keep a reference to a file that will be never be able to be downloaded

**Comment by iwanbk** [comment]
> Actual result: error saying that we can't find the key of the file.

How yo delete it?
minio dev said that we will got this if we use `mc rm`

i tried to use https://godoc.org/github.com/minio/minio-go#Client.RemoveObject it didn't get the error

>  But at least if we don't return an error we can actually clean up the bucket. If we don't allow this. We'll > keep a reference to a file that will be never be able to be downloaded

To do this, we will need to delete the metadata even though the delete operation failed.

**Comment by iwanbk** [comment]
@zaibon fixed at #33
