### ISSUE TITLE
recursive List Objects

### ISSUE THREAD

**Issue by iwanbk** [gigforks/minio#35]
It only list the files in the root dir, not the prefix and not the files in subdir

tested with `mc ls -r`

**Comment by iwanbk** [comment]
tested with `minio server`, the server indeed doesn't return the `prefixes`

**Comment by iwanbk** [comment]
@ahmedelsayed-93 support for list objects recursively added on e22fb6c5544c6c855c7b820afd0d343f6a49e8bf

please check

**Comment by ahmedelsayed-93** [comment]
verified
