### ISSUE TITLE
Rebase this fork on origin/master

### ISSUE THREAD

**Issue by zaibon** [gigforks/minio#51]
Should probably automate this in the Makefile or something

**Comment by iwanbk** [comment]
We can't do this for now, their gateway interface still not mature, still changing.

My first rebase got breaking changes. Same case with now.

**Comment by iwanbk** [comment]
done at 6a471d3397853b571779f6e6557e315cf89fa97b

**Comment by iwanbk** [comment]
How we provide context cancelation when 0-stor doesn't support it?
