### ISSUE TITLE
Propose our gateway implementation upstream

### ISSUE THREAD

**Issue by zaibon** [gigforks/minio#52]
Make sure our code follow their guideline and then propose for a merge upstream.

**Comment by iwanbk** [comment]
We can't propose it as long as we are still using etcd as defaul metastor of 0-stor.

I was thinking of using 0-metadata as default meta stor, but that project seems not progressing for a long time.

Using badger and filemeta as default 0-stor metastor is not good way i think. We need something reliable for metadata storage. Otherwise we provide user with non-reliable default system.

**Comment by zaibon** [comment]
Agree. And we know that we don't want to use etcd anyhow.

**Comment by zaibon** [comment]
Sounds good

**Comment by iwanbk** [comment]
- 0-stor has been updated
- passed the `make verifiers`

Now add the `encryption` to metadata, as reported at #58

**Comment by iwanbk** [comment]
did rebase from upstream, just before proposing the PR.

Got many errors, noticed changes:
- `errros` package was removed
- `cmd.NewLogger` was removed, there is new `logger` package
- `GetBucketPolicy` API change.

Now working on the required changes.
estimation : 1h

Also saw that another gateway has new features : drive cache.
Should adapt our gateway to this.
estimation : -

**Comment by iwanbk** [comment]
> BucketPolicy API change.
> Now working on the required changes.
> estimation : 1-2h

The BucketPolicy change is very confusing, two gateways i saw only allow to set policy to read only.

Now our bucket policy test is broken

> Also saw that another gateway has new features : drive cache.
> Should adapt our gateway to this.
> estimation : -

haven't tested it yet, but it seems that the cache functionality is fully handled by minio,  transparent from the gateway implementation.
So, we need to do almost nothing for this, only need to add the related help message.

**Comment by iwanbk** [comment]
> The BucketPolicy change is very confusing, two gateways i saw only allow to set policy to read only.

> Now our bucket policy test is broken

The bucket policy change was only done 2 days ago at https://github.com/gigforks/minio/commit/0d521260237ca69a89044f23f10a13b44e1f53c9

And it seems that the functionality is indeed still broken.  Tested with : 
- official minio client (`mc`)
- alibaba object storage service gateway

**Comment by zaibon** [comment]
is there already a PR on minio repo to propose our gateway ?

**Comment by iwanbk** [comment]
> is there already a PR on minio repo to propose our gateway ?

Not yet, i didn't fully work from Tuesday to Thursday for the reason i mentioned in telegram

Now get many issues because of recent changes
https://github.com/gigforks/minio/issues/52#issuecomment-384851801
