### ISSUE TITLE
use scylladb or other nosql db for minio metadata

### ISSUE THREAD

**Issue by iwanbk** [gigforks/minio#62]
**background**:
- the current filemeta was indeed only supposed for temporary solution. 
- while my test of using syncthing.net as replication still not find any issue (other than replication delay issue), i still **feel** that it is hacky solution. But to be fair, it might be good solution. I'm just still not sure with it

to add some context: filemeta has issue as described at #61, which might be solved  by improved version of #60.

**advantage of using nosqldb**
- unlike KV store such as etcd, we can add field to the entry/row. We can add 'parent' dir there
- we can use less/more operator to the key, which is needed for list object paging. We need it because the S3 paging is not using start index, but using key as marker
- we use battle tested replication provided by the nosqldb

I've tried scylladb CQL (cassandra queary language) , we can use it for paging.
i have some experience with mongodb. While i haven't tried it for our use case,  i think it could work.

cc: @FastGeert @muhamadazmy

**Comment by FastGeert** [comment]
@iwanbk Can you give an estimate of how much work it is to implement the metadata with mongodb?

**Comment by iwanbk** [comment]
> @iwanbk Can you give an estimate of how much work it is to implement the metadata with mongodb?

a working version should take no more than one day.
A good one might take 2 days.

**Comment by iwanbk** [comment]
A working version of mongodb based metadata has been pushed to `mongodb-meta` branch.

Remaining works:
- write proper unit tests
- add mongodb configuration to the configuration files

**Comment by FastGeert** [comment]
Cool, please finish up first completely before starting to work on the self-healing FR.

**Comment by iwanbk** [comment]
> please finish up first completely before starting to work on the self-healing FR.

oh, i already finished the hot reload config at #64. Could be merged soon.

For this mongodb, we can expect it to be finished completely tomorrow.

**Comment by iwanbk** [comment]
update today:
- added  unit tests for mongodb metadata. It uses same test file based metadata. So we can expect full compatibility
- add metadata configuration to file config.

While it is already complete, i will only send the PR after we also move the multipart upload manager to use mongodb. ETA : 1 day

**Comment by iwanbk** [comment]
Implemented in #67
